server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 39.105.xxx.x
                port: xxxx
                username: xx
                password: xx
      bindings: # 服务的整合处理
        input: # 通道名
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，文本设置为"text/plain"
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: ${spring.application.name} # 指定分组，即对应队列

#Eureka配置
eureka:
  client:
    register-with-eureka: true # 表示是否向注册中心注册当前服务
    fetch-registry: true # 表示是否需要去注册中心获取其他服务地址
    service-url: # 设置与Eureka Server交互的地址查询服务 和 注册服务 依赖的网关地址
      defaultZone: http://localhost:7001/eureka

logging:
  level:
    com: INFO
