server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: cloud-payment-service # 路由的ID, 没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配动态路由地址
          predicates:
            - Path=/cloud-payment-service/** # 断言， 路径相匹配的进行路由
          filters:
            - StripPrefix=1

#Eureka配置
eureka:
  client:
    register-with-eureka: true # 表示是否向注册中心注册当前服务
    fetch-registry: true # 表示是否需要去注册中心获取其他服务地址
    service-url: # 设置与Eureka Server交互的地址查询服务 和 注册服务 依赖的网关地址
      defaultZone: http://localhost:7001/eureka
