server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wang936221

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wangdong.payment.pojo.entities

#Eureka配置
eureka:
  client:
    register-with-eureka: true # 表示是否向注册中心注册当前服务
    fetch-registry: true # 表示是否需要去注册中心获取其他服务地址
    service-url: # 设置与Eureka Server交互的地址查询服务 和 注册服务 依赖的网关地址
      defaultZone: http://localhost:7001/eureka

feign:
  hystrix:
    enabled: true

#设置Feign客户端超时时间
#ribbon:
#  ReadTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ConnectTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间

logging:
  level:
    com: info
